### ISSUE TITLE
How can I get /run/media/airalcorn2/MiQ BIG/ShapeNetCore.v2?

### ISSUE THREAD

**Issue by Cassiatora** [airalcorn2/pytorch-nerf#1]
I want to run the generate_pixelnerf_dataset. But I can't access the /run/media/airalcorn2/MiQ BIG/ShapeNetCore.v2
.

**Comment by airalcorn2** [comment]
See the instructions [here](https://github.com/airalcorn2/pytorch-nerf#generating-the-shapenet-datasets).
