### ISSUE TITLE
what is the camera distance?

### ISSUE THREAD

**Issue by lebronMessi** [airalcorn2/pytorch-nerf#4]
Hello,can you tell me what is the camera_distance in your code .In my own dataset,how to get the camera_distance.

**Comment by airalcorn2** [comment]
The `camera_distance` is the camera's distance from the origin (where the object is placed for the renderer) and is used to set up the [LookAt matrix](https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/lookat-function) for the renderer [here](https://github.com/airalcorn2/pytorch-nerf/blob/master/renderer.py#L359).
