### ISSUE TITLE
question about the elevation

### ISSUE THREAD

**Issue by FENGGENYU** [airalcorn2/pytorch-nerf#7]
Hi, thank you for this wonderful simple version of Nerf for starters.

One quick question about setting the range of elevation and azimuth at [line 42-43](https://github.com/airalcorn2/pytorch-nerf/blob/fe0055885a40f7bbc1c4b0a1c51437601870f6bc/generate_nerf_dataset.py#L42).

Why do you set both range in (-pi, pi)? I think setting up the range (-pi/2,pi/2) should be enough for elevation.

Thank you in advance for the clarification.

**Comment by airalcorn2** [comment]
Thanks for the kind words. I honestly probably just wasn't paying attention. What I'm doing there actually isn't uniformly sampling camera angles either, so I'll fix that in a commit.
