### ISSUE TITLE
How to render novel views ?

### ISSUE THREAD

**Issue by AvishkarArjan** [airalcorn2/pytorch-nerf#9]
I checked out the code for run_nerf.py in google colab, but it is only training on a single test view image.
I am a beginner so I kinda feel like the NeRF isnt doing what its supposed to. It should be trained on multiple views for a scene and then generate novel views from different queried directions?

How can I optimize the code or the code for run_tiny_nerf.py to train it on different views of a scene and render novel views from the model ??

**Comment by airalcorn2** [comment]
[The model is trained on multiple views](https://github.com/airalcorn2/pytorch-nerf/blob/c9a055558e57c14bf51429811e40ff90331ba87b/run_nerf.py#L268) and [renders a novel view](https://github.com/airalcorn2/pytorch-nerf/blob/c9a055558e57c14bf51429811e40ff90331ba87b/run_nerf.py#L318). The dataset was generated using [`generate_nerf_dataset.py`](https://github.com/airalcorn2/pytorch-nerf/blob/master/generate_nerf_dataset.py) as [described in the README](https://github.com/airalcorn2/pytorch-nerf#generating-the-shapenet-datasets).

**Comment by AvishkarArjan** [comment]
Thanks for clearing it out, guess I got confused, I get it now 👍
